In [ ]:
from getpass import getpass

# Prompt for token securely
token = getpass('Enter your GitHub personal access token: ')

# Clone using token authentication
!git clone https://{token}@github.com/pabasara-samarakoon-4176/MDT_prediction.git

Enter your GitHub personal access token: ··········
Cloning into 'MDT_prediction'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 3 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), 15.69 KiB | 7.84 MiB/s, done.


In [ ]:
!ls /content/drive/MyDrive/Colab\ Notebooks/fyp_model.ipynb

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
filename = "/content/drive/MyDrive/Final_year_project/geohash_8_512_v1.csv"
df = pd.read_csv(filename)

In [ ]:
df = df.drop(columns=['geometry'])

In [ ]:
df.head()

Geohash  Latitude  Longitude     Azimuth      Tilt     Height  \
0  tc336yf5   7.28862   80.63172   62.517379  5.720492  31.771188   
1  tc336yfh   7.28880   80.63172  162.588252 -5.099024  46.024366   
2  tc336yfj   7.28898   80.63172  137.861641 -4.707110  58.411123   
3  tc336yfn   7.28916   80.63172  359.779339  3.532819  56.358266   
4  tc336yfp   7.28934   80.63172  256.187669  0.216671  14.842767   

   Distance_to_cell  Avg_Angle_with_cell      NDVI  RoadDensity   Elevation  \
0        262.963774            49.354578  0.046117     0.892990  257.245749   
1        161.274774            30.028302  0.210933     0.955532  290.039403   
2        335.148634            15.474290  0.200916     0.638547  238.689121   
3        260.509491            73.777133  0.800344     0.348175  110.591211   
4        208.098760             3.911508  0.585279     0.387504  267.052850   

         RSRP  
0  -99.711965  
1  -98.530285  
2 -105.569320  
3 -116.536623  
4 -113.683020

In [ ]:
df.columns

Index(['Geohash', 'Latitude', 'Longitude', 'Azimuth', 'Tilt', 'Height',
       'Distance_to_cell', 'Avg_Angle_with_cell', 'NDVI', 'RoadDensity',
       'Elevation', 'RSRP'],
      dtype='object')

In [ ]:
geohash_vocab = {g: i for i, g in enumerate(df['Geohash'].unique())}
df['Geohash_index'] = df['Geohash'].map(geohash_vocab)

In [ ]:
df.head()

Geohash  Latitude  Longitude     Azimuth      Tilt     Height  \
0  tc336yf5   7.28862   80.63172   62.517379  5.720492  31.771188   
1  tc336yfh   7.28880   80.63172  162.588252 -5.099024  46.024366   
2  tc336yfj   7.28898   80.63172  137.861641 -4.707110  58.411123   
3  tc336yfn   7.28916   80.63172  359.779339  3.532819  56.358266   
4  tc336yfp   7.28934   80.63172  256.187669  0.216671  14.842767   

   Distance_to_cell  Avg_Angle_with_cell      NDVI  RoadDensity   Elevation  \
0        262.963774            49.354578  0.046117     0.892990  257.245749   
1        161.274774            30.028302  0.210933     0.955532  290.039403   
2        335.148634            15.474290  0.200916     0.638547  238.689121   
3        260.509491            73.777133  0.800344     0.348175  110.591211   
4        208.098760             3.911508  0.585279     0.387504  267.052850   

         RSRP  Geohash_index  
0  -99.711965              0  
1  -98.530285              1  
2 -105.569320              2  
3 -116.536623              3  
4 -113.683020              4

In [ ]:
from sklearn.preprocessing import StandardScaler

features = ['Latitude', 'Longitude', 'Azimuth', 'Tilt', 'Height',
            'Distance_to_cell', 'Avg_Angle_with_cell', 'NDVI',
            'RoadDensity', 'Elevation']

scaler = StandardScaler()
df[features] = scaler.fit_transform(df[features])

In [ ]:
# prompt: Get the minimum and maximum of `df['RSRP']`.

min_rsrp = df['RSRP'].min()
max_rsrp = df['RSRP'].max()

print(f"Minimum RSRP: {min_rsrp}")
print(f"Maximum RSRP: {max_rsrp}")

Minimum RSRP: -132.07607933703306
Maximum RSRP: -85.09598354727335


In [ ]:
rsrp_scaler = StandardScaler()
df['RSRP_norm'] = rsrp_scaler.fit_transform(df[['RSRP']])

In [ ]:
df.head()

Geohash  Latitude  Longitude   Azimuth      Tilt    Height  \
0  tc336yf5 -1.636701  -1.654629 -1.143246  1.148195 -0.204132   
1  tc336yfh -1.486550  -1.654629 -0.176027 -0.801477  0.785217   
2  tc336yfj -1.336399  -1.654629 -0.415019 -0.730855  1.645014   
3  tc336yfn -1.186249  -1.654629  1.729891  0.753977  1.502520   
4  tc336yfp -1.036098  -1.654629  0.728643  0.156409 -1.379177   

   Distance_to_cell  Avg_Angle_with_cell      NDVI  RoadDensity  Elevation  \
0          0.079244             0.226369 -1.462252     1.373481   0.955847   
1         -0.630166            -0.524988 -0.848007     1.593722   1.471091   
2          0.582826            -1.090811 -0.885336     0.477450   0.664290   
3          0.062123             1.175856  1.348651    -0.545107  -1.348347   
4         -0.303509            -1.540343  0.547130    -0.406607   1.109933   

         RSRP  Geohash_index  RSRP_norm  
0  -99.711965              0   0.998814  
1  -98.530285              1   1.125492  
2 -105.569320              2   0.370895  
3 -116.536623              3  -0.804821  
4 -113.683020              4  -0.498909

In [ ]:
import torch

input_tensor = torch.tensor(df[features + ['Geohash_index']].values, dtype=torch.float32)
target_tensor = torch.tensor(df['RSRP_norm'].values, dtype=torch.float32).view(-1, 1)

In [ ]:
def positional_encoding(seq_len, d_model):
    pos = torch.arange(seq_len, dtype=torch.float32).unsqueeze(1)
    i = torch.arange(d_model, dtype=torch.float32).unsqueeze(0)
    angle_rates = 1 / torch.pow(10000, (2 * (i // 2)) / d_model)
    angle_rads = pos * angle_rates

    pos_encoding = torch.zeros(seq_len, d_model)
    pos_encoding[:, 0::2] = torch.sin(angle_rads[:, 0::2])
    pos_encoding[:, 1::2] = torch.cos(angle_rads[:, 1::2])
    return pos_encoding

In [ ]:
!pip install geohash2

  Preparing metadata (setup.py) ... done
  Created wheel for geohash2: filename=geohash2-1.1-py3-none-any.whl size=15543 sha256=8598e89fb5247ae55bca1f61b4663f8f0fed995bbe4a0d50f9572053413e5307
  Stored in directory: /root/.cache/pip/wheels/f6/7c/c4/1b3c6fea0ebc53bf730dc86bbee7a713d501455dfb4c1f0623
Successfully built geohash2


In [ ]:
import geohash2

def geohash_to_position_tensor(geohash_list):
    """Convert a list of geohashes to positional encoding via lat/lon"""
    positions = [(float(lat), float(lon)) for lat, lon in [geohash2.decode(g) for g in geohash_list]]
    pos_tensor = torch.tensor(positions, dtype=torch.float32)  # [N, 2]
    return pos_tensor

In [ ]:
from torch import nn

geohash_positions = geohash_to_position_tensor(df['Geohash'].tolist())

In [ ]:
geohash_positions

tensor([[ 7.2890, 80.6320],
        [ 7.2890, 80.6320],
        [ 7.2890, 80.6320],
        ...,
        [ 7.2890, 80.6360],
        [ 7.2890, 80.6360],
        [ 7.2900, 80.6360]])

In [ ]:
position_projector = nn.Linear(2, 11)
position_embeddings = position_projector(geohash_positions)

In [ ]:
position_embeddings[0]

tensor([-42.1278, -54.8047,  23.0147,   0.1177,  40.0538, -52.4713,  -8.1670,
         42.8483,  51.4816,   4.4873, -26.7261], grad_fn=<SelectBackward0>)

In [ ]:
position_embeddings.shape

torch.Size([512, 11])

In [ ]:
input_tensor_pos = input_tensor + position_embeddings

In [ ]:
input_tensor_pos.shape

torch.Size([512, 11])

In [ ]:
input_tensor = input_tensor_pos.unsqueeze(1)

In [ ]:
input_tensor.shape

torch.Size([512, 1, 11])

In [ ]:
project = nn.Linear(11, 64)
projected_input = project(input_tensor)

In [ ]:
projected_input.shape

torch.Size([512, 1, 64])

In [ ]:
#single-head
d_model = 64
d_k = 64
d_v = 64

In [ ]:
W_q = nn.Linear(d_model, d_k)
W_k = nn.Linear(d_model, d_k)
W_v = nn.Linear(d_model, d_v)

In [ ]:
Q = W_q(projected_input)
K = W_k(projected_input)
V = W_v(projected_input)

In [ ]:
# Attention
import torch.nn.functional as F

attention_scores = Q @ K.transpose(-2, -1) / torch.sqrt(torch.tensor(d_k))
attention_weigths = F.softmax(attention_scores, dim=-1)
attention_output = attention_weigths @ V

In [ ]:
projected_input.shape

torch.Size([512, 1, 64])

In [ ]:
attention_output.shape

torch.Size([512, 1, 64])

In [ ]:
# Residual block 1
layer_norm = nn.LayerNorm(d_model)
residual_1 = layer_norm(projected_input + attention_output)

In [ ]:
# FFN
d_ff = 2
ffn_output = nn.Sequential(
    nn.Linear(d_model, d_ff),
    nn.ReLU(),
    nn.Linear(d_ff, d_model)
)(residual_1)

In [ ]:
ffn_output.shape

torch.Size([512, 1, 64])

In [ ]:
residual_2 = layer_norm(residual_1 + ffn_output)

In [ ]:
residual_2.shape

torch.Size([512, 1, 64])

In [ ]:
x = residual_2.squeeze(1)

In [ ]:
x.shape

torch.Size([512, 64])

In [ ]:
output_layer = nn.Linear(d_model, 1)

In [ ]:
rsrp_preds = output_layer(x)

In [ ]:
rsrp_preds[:10]

tensor([[-0.1860],
        [-0.1889],
        [-0.2024],
        [-0.2066],
        [-0.1997],
        [-0.1981],
        [-0.2040],
        [-0.1973],
        [-0.2073],
        [-0.2056]], grad_fn=<SliceBackward0>)

In [ ]:
# prompt: get the maximum and minimum values of the `rsrp_preds`.

print(f"Minimum RSRP prediction: {torch.min(rsrp_preds)}")
print(f"Maximum RSRP prediction: {torch.max(rsrp_preds)}")

Minimum RSRP prediction: -0.3633665442466736
Maximum RSRP prediction: -0.18596398830413818


In [ ]:
target_tensor.shape

torch.Size([512, 1])

In [ ]:
rsrp_preds.shape

torch.Size([512, 1])

In [ ]:
# Assuming you have this from earlier
rsrp_pred_np = rsrp_preds.detach().numpy()
target_np = target_tensor.detach().numpy()

# Inverse transform both
rsrp_pred_actual = rsrp_scaler.inverse_transform(rsrp_pred_np)
target_actual = rsrp_scaler.inverse_transform(target_np)

In [ ]:
rsrp_pred_actual[:10]

array([[-110.76381 ],
       [-110.79155 ],
       [-110.916664],
       [-110.95669 ],
       [-110.89212 ],
       [-110.87734 ],
       [-110.93243 ],
       [-110.869965],
       [-110.962425],
       [-110.94728 ]], dtype=float32)

In [ ]:
target_actual[:10]

array([[ -99.71197],
       [ -98.53029],
       [-105.56932],
       [-116.53662],
       [-113.68302],
       [-105.9487 ],
       [-126.81516],
       [ -90.71553],
       [-130.1712 ],
       [ -93.02869]], dtype=float32)

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

rmse = np.sqrt(mean_squared_error(target_actual, rsrp_pred_actual))
mae = mean_absolute_error(target_actual, rsrp_pred_actual)
r2 = r2_score(target_actual, rsrp_pred_actual)

print(f"RMSE: {rmse:.2f} dBm")
print(f"MAE: {mae:.2f} dBm")
print(f"R² Score: {r2:.4f}")

RMSE: 9.78 dBm
MAE: 8.01 dBm
R² Score: -0.0988


In [ ]:
# complete model
import torch
from torch import nn
import torch.nn.functional as F
import math

class RSRPTransformerModel(nn.Module):
    def __init__(self, input_dim=11, d_model=64, d_ff=2, output_dim=1):
        super(RSRPTransformerModel, self).__init__()
        self.d_model = d_model
        self.input_proj = nn.Linear(input_dim, d_model)

        # Positional Encoding from Geohash (Lat, Lon → d_model)
        self.position_proj = nn.Linear(2, input_dim)

        # Self-attention weights
        self.W_q = nn.Linear(d_model, d_model)
        self.W_k = nn.Linear(d_model, d_model)
        self.W_v = nn.Linear(d_model, d_model)

        # LayerNorm
        self.layer_norm1 = nn.LayerNorm(d_model)
        self.layer_norm2 = nn.LayerNorm(d_model)

        # Feedforward network
        self.ffn = nn.Sequential(
            nn.Linear(d_model, d_ff),
            nn.ReLU(),
            nn.Linear(d_ff, d_model)
        )

        # Output layer for RSRP prediction
        self.output_layer = nn.Linear(d_model, output_dim)

    def forward(self, x, geohash_pos_tensor):
        # Positional encoding projection
        pos_embed = self.position_proj(geohash_pos_tensor)
        x = x + pos_embed  # Inject position (geohash-derived) info

        # Add sequence dimension
        x = x.unsqueeze(1)  # Shape: [N, 1, input_dim]

        # Project input to d_model
        x_proj = self.input_proj(x)  # Shape: [N, 1, d_model]

        # Compute attention
        Q = self.W_q(x_proj)
        K = self.W_k(x_proj)
        V = self.W_v(x_proj)

        attention_scores = Q @ K.transpose(-2, -1) / math.sqrt(self.d_model)
        attention_weights = F.softmax(attention_scores, dim=-1)
        attention_output = attention_weights @ V

        # Residual + Norm
        res_1 = self.layer_norm1(x_proj + attention_output)

        # Feedforward
        ffn_output = self.ffn(res_1)
        res_2 = self.layer_norm2(res_1 + ffn_output)

        # Squeeze sequence dimension
        res_2 = res_2.squeeze(1)  # Shape: [N, d_model]

        # Predict RSRP
        return self.output_layer(res_2)

In [ ]:
model = RSRPTransformerModel(input_dim=11, d_model=64)

In [ ]:
import torch

input_tensor = torch.tensor(df[features + ['Geohash_index']].values, dtype=torch.float32)
target_tensor = torch.tensor(df['RSRP_norm'].values, dtype=torch.float32).view(-1, 1)

In [ ]:
geohash_pos_tensor = geohash_to_position_tensor(df['Geohash'].tolist())

In [ ]:
x = input_tensor
rsrp_preds = model(x, geohash_pos_tensor)

In [ ]:
rsrp_preds.shape

torch.Size([512, 1])

In [ ]:
# Assuming you have this from earlier
rsrp_pred_np = rsrp_preds.detach().numpy()
target_np = target_tensor.detach().numpy()

# Inverse transform both
rsrp_pred_actual = rsrp_scaler.inverse_transform(rsrp_pred_np)
target_actual = rsrp_scaler.inverse_transform(target_np)

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

rmse = np.sqrt(mean_squared_error(target_actual, rsrp_pred_actual))
mae = mean_absolute_error(target_actual, rsrp_pred_actual)
r2 = r2_score(target_actual, rsrp_pred_actual)

print(f"RMSE: {rmse:.2f} dBm")
print(f"MAE: {mae:.2f} dBm")
print(f"R² Score: {r2:.4f}")

RMSE: 13.73 dBm
MAE: 11.40 dBm
R² Score: -1.1653


In [ ]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df, test_size=0.2, random_state=42
)

In [ ]:
# Training
x = torch.tensor(train_df[features + ['Geohash_index']].values, dtype=torch.float32)
geohash_pos_tensor = geohash_to_position_tensor(train_df['Geohash'].tolist())
target_tensor = torch.tensor(train_df['RSRP_norm'].values, dtype=torch.float32).view(-1, 1)

In [ ]:
model = RSRPTransformerModel(input_dim=11, d_model=64)

In [ ]:
import torch.nn as nn
import torch.optim as optim

loss_fn = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

In [ ]:
num_epochs = 100

for epoch in range(num_epochs):
  model.train()
  # Forward pass
  preds = model(x, geohash_pos_tensor)
  loss = loss_fn(preds, target_tensor)
  # Backward pass
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  if (epoch + 1) % 10 == 0 or epoch == 0:
      print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

Epoch [1/100], Loss: 1.0824
Epoch [10/100], Loss: 1.0680
Epoch [20/100], Loss: 1.0653
Epoch [30/100], Loss: 1.0601
Epoch [40/100], Loss: 1.0583
Epoch [50/100], Loss: 1.0577
Epoch [60/100], Loss: 1.0567
Epoch [70/100], Loss: 1.0558
Epoch [80/100], Loss: 1.0548
Epoch [90/100], Loss: 1.0539
Epoch [100/100], Loss: 1.0529


In [ ]:
# Features and target
features = ['Latitude', 'Longitude', 'Azimuth', 'Tilt', 'Height',
            'Distance_to_cell', 'Avg_Angle_with_cell', 'NDVI',
            'RoadDensity', 'Elevation']

# Use the scaler already fitted on `train_df`
X_test = test_df[features]
geohash_positions_test = geohash_to_position_tensor(test_df['Geohash'].tolist())

# Convert to tensors
input_tensor_test = torch.tensor(
    np.hstack([X_test, test_df[['Geohash_index']].values]), dtype=torch.float32
)
geohash_pos_test = geohash_positions_test

# Target tensor (normalized)
target_tensor_test = torch.tensor(
    test_df['RSRP_norm'].values, dtype=torch.float32).view(-1, 1)

In [ ]:
model.eval()
with torch.no_grad():
    preds_test = model(input_tensor_test, geohash_pos_test)

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Denormalize if needed
rsrp_pred_denorm = rsrp_scaler.inverse_transform(preds_test.numpy())
target_denorm = rsrp_scaler.inverse_transform(target_tensor_test.numpy())

# Metrics
mse = mean_squared_error(target_denorm, rsrp_pred_denorm)
mae = mean_absolute_error(target_denorm, rsrp_pred_denorm)
r2 = r2_score(target_denorm, rsrp_pred_denorm)

print(f"Test MSE: {mse:.4f}")
print(f"Test MAE: {mae:.4f}")
print(f"Test R²:  {r2:.4f}")

Test MSE: 65.3847
Test MAE: 6.6710
Test R²:  -0.0020
